CREATE TABLE contact_us (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  phone_number VARCHAR(30) NULL,
  whatsapp_number VARCHAR(30) NULL,
  messenger_link VARCHAR(500) NULL,
  email VARCHAR(191) NULL,
  address TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
