CREATE TABLE account_coa (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, HeadCode BIGINT UNSIGNED NOT NULL, HeadName VARCHAR(100) NOT NULL, PHeadName VARCHAR(100) NULL, parent_id BIGINT UNSIGNED NULL, HeadLevel INT NOT NULL DEFAULT 0, IsActive BOOLEAN NOT NULL DEFAULT TRUE, IsTransaction BOOLEAN NOT NULL DEFAULT FALSE, IsGL BOOLEAN NOT NULL DEFAULT FALSE, IsJournal BOOLEAN NOT NULL DEFAULT FALSE, HeadType CHAR(1) NULL, IsBudget BOOLEAN NOT NULL DEFAULT FALSE, IsDepreciation BOOLEAN NOT NULL DEFAULT FALSE, customer_id BIGINT UNSIGNED NULL, aggre_id BIGINT UNSIGNED NULL, supplier_id BIGINT UNSIGNED NULL, employee_id BIGINT UNSIGNED NULL, payment_method_id VARCHAR(255) NULL, bank_id VARCHAR(255) NULL, node_type ENUM('root','group','control','ledger') NOT NULL DEFAULT 'group', allows_manual_children BOOLEAN NOT NULL DEFAULT FALSE, is_system BOOLEAN NOT NULL DEFAULT FALSE, CreateBy VARCHAR(50) NULL, CreateDate DATE NULL, UpdateBy VARCHAR(50) NULL, UpdateDate DATE NULL, deleted_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY account_coa_head_code_unique(HeadCode), KEY account_coa_parent_index(parent_id), CONSTRAINT account_coa_parent_fk FOREIGN KEY(parent_id) REFERENCES account_coa(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO account_coa (HeadCode,HeadName,PHeadName,HeadLevel,IsActive,IsTransaction,IsGL,IsJournal,HeadType,node_type,allows_manual_children,is_system,CreateBy,CreateDate) VALUES
(1,'COA',NULL,0,1,0,1,0,NULL,'root',1,1,'Seeding',CURDATE()),(100,'Assets','COA',1,1,0,1,0,'A','group',1,1,'Seeding',CURDATE()),(10001,'Current Assets','Assets',2,1,0,1,0,'A','group',1,1,'Seeding',CURDATE()),(10002,'Non-Current Assets','Assets',2,1,0,1,0,'A','group',1,1,'Seeding',CURDATE()),(1000101,'Cash in Hand','Current Assets',3,1,1,0,1,'A','ledger',0,1,'Seeding',CURDATE()),(1000102,'Cash at Bank','Current Assets',3,1,0,0,1,'A','ledger',0,1,'Seeding',CURDATE()),(1000103,'Cash in Bkash','Current Assets',3,1,0,0,1,'A','ledger',0,1,'Seeding',CURDATE()),(1000104,'Cash in Nagad','Current Assets',3,1,0,0,1,'A','ledger',0,1,'Seeding',CURDATE()),(1000108,'Inventory','Current Assets',3,1,0,1,0,'A','group',0,1,'Seeding',CURDATE()),(1000109,'Customer Receivable','Current Assets',3,1,0,1,0,'A','control',0,1,'Seeding',CURDATE()),(1000110,'Supplier Advance','Current Assets',3,1,0,1,0,'A','control',0,1,'Seeding',CURDATE()),
(200,'Liabilities','COA',1,1,0,1,0,'L','group',1,1,'Seeding',CURDATE()),(20001,'Current Liabilities','Liabilities',2,1,0,1,0,'L','group',1,1,'Seeding',CURDATE()),(20002,'Long Term Liabilities','Liabilities',2,1,0,1,0,'L','group',1,1,'Seeding',CURDATE()),(2000101,'Supplier Payable','Current Liabilities',3,1,0,1,0,'L','control',0,1,'Seeding',CURDATE()),(2000102,'Salaries Payable','Current Liabilities',3,1,0,1,0,'L','control',0,1,'Seeding',CURDATE()),(2000103,'Utilities Payable','Current Liabilities',3,1,0,1,0,'L','ledger',0,1,'Seeding',CURDATE()),(2000104,'Vat Tax Payable','Current Liabilities',3,1,0,1,0,'L','ledger',0,1,'Seeding',CURDATE()),
(300,'Owners Equity','COA',1,1,0,1,0,'O','group',1,1,'Seeding',CURDATE()),(30001,'Capital','Owners Equity',2,1,0,1,0,'O','ledger',0,1,'Seeding',CURDATE()),(30002,'Retained Earning','Owners Equity',2,1,0,1,0,'O','ledger',0,1,'Seeding',CURDATE()),(400,'Income','COA',1,1,0,1,0,'I','group',1,1,'Seeding',CURDATE()),(40001,'Sales','Income',2,1,0,1,0,'I','group',1,1,'Seeding',CURDATE()),(4000101,'Product Sale','Sales',3,1,1,0,1,'I','ledger',0,1,'Seeding',CURDATE()),(40002,'Other Income','Income',2,1,1,0,1,'I','ledger',0,1,'Seeding',CURDATE()),
(500,'Expenses','COA',1,1,0,1,0,'E','group',1,1,'Seeding',CURDATE()),(50001,'Direct Cost / COGS','Expenses',2,1,0,1,0,'E','group',1,1,'Seeding',CURDATE()),(50002,'Operating Expenses','Expenses',2,1,0,1,0,'E','group',1,1,'Seeding',CURDATE()),(5000101,'Purchase Cost','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000102,'Freight/Transport Cost','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000103,'Custom Duty','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000104,'Shipping Cost','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000105,'LC Charges','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000106,'Other Landing Cost','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000107,'Cost of Goods Sold','Direct Cost / COGS',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000201,'Office Rent','Operating Expenses',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000203,'Salary Expenses','Operating Expenses',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000204,'Electricity Bill','Operating Expenses',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE()),(5000206,'Internet Bill','Operating Expenses',3,1,1,0,1,'E','ledger',0,1,'Seeding',CURDATE());
CREATE TEMPORARY TABLE account_coa_parent_map AS SELECT id,HeadName FROM account_coa;
UPDATE account_coa child JOIN account_coa_parent_map parent ON parent.HeadName=child.PHeadName SET child.parent_id=parent.id WHERE child.PHeadName IS NOT NULL;
DROP TEMPORARY TABLE account_coa_parent_map;
