CREATE TABLE banks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(150) NOT NULL, account_name VARCHAR(150) NOT NULL,
  account_number VARCHAR(100) NOT NULL, branch VARCHAR(150) NULL, routing_number VARCHAR(100) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id), UNIQUE KEY banks_account_number_unique(account_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
